MODEL:
  ENCODER:
    NAME: 'mlp'                #  'mlp' | 'tf'
    INPUT_SIZE: 47
    OUTPUT_SIZE: 512
    DROPOUT: 0.2
    # For MLP
    # HIDDEN_SIZE: 512
    # For Transformer
    NHEAD: 8
    HIDDEN_SIZE: 512
    NUM_LAYERS: 6
  HEAD:
    CLASSIFIER:
      HIDDEN_SIZE: 128
      OUTPUT_SIZE: 3
      DROPOUT: 0.2
    REGRESSOR:
      HIDDEN_SIZE: 128
      OUTPUT_SIZE: 1
      DROPOUT: 0.2
DATASETS:
  TRAIN: "train.csv"
  VAL: "validation.csv"
  TEST: "test.csv"
SOLVER:
  EPOCHS: 300
  BATCH_SIZE: 64
  BASE_LR: 1.5e-4
  WEIGHT_DECAY: 0.001
  GPUS: [4,5,6,7]
  OPTIMIZER: 'AdamW'        # SGD | AdamW
  LR_SCHEDULER: 'CosineAnnealingLR'     # MultiStepLR | CosineAnnealingLR | WarmupCosineLR
  MILESTONES: [200]         # MultiStepLR
  GAMMA: 0.1                # MultiStepLR
  MIN_LR: 1e-6              # CosineAnnealingLR
WANDB:
  ENABLE: True
  NAME: 'debug'
  GROUP: 'source'
  PROJECT: 'uda_particle_simul'
  ENTITY: 'pinlab-sapienza'
OUTPUT_DIR: 'results/source/debug'
PROTOCOL: 'source'