MODEL:
  ENCODER:
    NAME: 'mlp'                #  'mlp' | 'tf'
    INPUT_SIZE: 47
    OUTPUT_SIZE: 256
    DROPOUT: 0.1
    HIDDEN_SIZE: 512
    NUM_LAYERS: 6
    # For Transformer
    # NHEAD: 8
  HEAD:
    CLASSIFIER:
      HIDDEN_SIZE: 256
      OUTPUT_SIZE: 1          # 0: elettrone, 1: protone
      DROPOUT: 0.
    REGRESSOR:
      HIDDEN_SIZE: 256
      OUTPUT_SIZE: 2
      DROPOUT: 0.
DATASETS:
  TRAIN: "data/source/dataset_train.csv"
  VAL: "data/source/dataset_validation.csv"
  TEST: "data/source/dataset_test.csv"
SOLVER:
  EPOCHS: 300
  BATCH_SIZE: 512
  BASE_LR: 1e-3
  WEIGHT_DECAY: 2e-5
  GPUS: [0,1,2,3]
  OPTIMIZER: 'AdamW'        # SGD | AdamW
  LR_SCHEDULER: 'StepLR'     # StepLR | MultiStepLR | CosineAnnealingLR | WarmupCosineLR
  MILESTONES: [100, 200]         # MultiStepLR
  GAMMA: 0.95                # StepLR | MultiStepLR
  MIN_LR: 1e-6              # CosineAnnealingLR
VAL:
  BATCH_SIZE: 512
WANDB:
  ENABLE: False
  NAME: 'MLP Encoder'
  GROUP: 'source'
  PROJECT: 'uda_particle_simul'
  ENTITY: 'particlesim'
OUTPUT_DIR: 'results/source/mlp_encoder'
PROTOCOL: 'source'
SEED: -1